name: Integrity Check (Primitive Data)

on:
  push:
    branches: [ main ]
jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: 'true'
    - name: "Install packages"
      run: |
        sudo apt-get update
        sudo apt-get install graphviz-dev util-linux
    - name: Set up Latest Python Version
      uses: actions/setup-python@v2
      with:
        python-version: "3.x"
    - name: Install generator dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./requirements.txt
    - name: Generate Library
      run: |
        mkdir build
        cd build
        cmake ..
        make
        
