name: Published

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout TVL repository (recursive)
      uses: actions/checkout@v3
      with:
        repository: db-tu-dresden/TVLGen.git
        ref: main
        token: '${{ secrets.DHTVL_AT }}'
        submodules: recursive
    - name: Setup Git Creds
      run: |
        git config --global user.email "johannes.pietrzyk@tu-dresden.de"
        git config --global user.name "GitHub Action (Maintainer: Johannes Pietrzyk)"
    - name: Update TVL generator repository
      run: |
        git submodule foreach -q --recursive 'branch="$(git config -f $toplevel/.gitmodules submodule.$name.branch)"; git switch $branch'
        git add primitive_data
        git commit -m "Updated submodule primitive_data"
        git push
